_stock_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('accounts/', include('useraccounts.urls')),
    path('sales/', include('sales.urls')),
    path('notifications/', include('notifications.urls')),
    path('inventory/', include('inventory.urls')),
    path('', include('dashboard.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path 

from . import views


urlpatterns = [
    path('', views.notifications_view, name='notifications'),
]

sales/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.sales_list_view, name='sales_list'),
    path('create', views.sale_add_view, name='add_sale')
]

notifications/models.py
import uuid
from django.db import models

from useraccounts.models import User
from products.models import Product
from sales.models import Sale

class StatusChoices(models.TextChoices):
    orange = 'O', 'orange'
    green = 'G', 'green'
    red = 'R', 'red'


class NotificationTypeChoices(models.TextChoices):
    base = 'D', 'Base Notification'
    low_stock = 'A', 'Alerte Stock Faible'
    inventory_update = 'C', "Mis a jour de l'Inventaire"
    sale_record = 'B', "Notification de Vente"


class Notification(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    status = models.CharField(max_length=1, choices=StatusChoices.choices, default=StatusChoices.green)
    target = models.ManyToManyField(User, related_name='notifications')
    type = models.CharField(max_length=1, choices=NotificationTypeChoices.choices, default=NotificationTypeChoices.base)
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, related_name='notifications', null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='notifications', null=True)
    date = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=500)

    class Meta:
        ordering = ['type', '-date']


class LowStockNotification(Notification):
    class Meta:
        proxy = True 

    def save(self, *args, **kwargs):
        self.type = NotificationTypeChoices.low_stock
        self.status = StatusChoices.red
        self.body = f'Le Produit "{ self.product.name} | { self.product.get_brand_display()}" est en dessous du stock minimale. Stock restant: { self.product.quantity }.'
        return super().save(*args, **kwargs)
    

class InventoryUpdateNotification(Notification):
    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        self.type = NotificationTypeChoices.inventory_update
        self.status = StatusChoices.orange
        self.body = f'Le Stock du produit "{ self.product.name } | {self.product.get_brand_display()}" a ete mis a jour. Nouvelle quantite: { self.product.quantity }.'
        return super().save(*args, **kwargs)


class SaleRecordNotification(Notification):
    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        self.status = StatusChoices.green
        self.type = NotificationTypeChoices.sale_record
        self.body = f'Vente de  { self.sale.quantity } "{ self.sale.product.name} | {self.sale.product.get_brand_display() }" par { self.sale.done_by.name }.'
        return super().save(*args, **kwargs)
    

















    

notifications/views.py
from django.shortcuts import render

from notifications.models import Notification

def notifications_view(request):
    notifications = Notification.objects.filter(target__in=[request.user])[:12]
    return render(request, 'notifications/notifications.html', {'notifications': notifications})

templates/notifications/notifications.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Notifications - Stock Management{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'sidebar.css' %}">
<link rel="stylesheet" href="{% static 'notifications/notifications.css' %}">
{% endblock %}

{% block sidebar %}
{% include '../utils/sidebar.html' with active='notifications' %}
{% endblock %}

{% block content %}
<div class="main-content">
    <div class="header">
        <h1>Notifications</h1>
    </div>
    <div class="notifications-grid">
        <!-- Notification Cards -->
        {% for notification in notifications %}
        <div class="notification-card {{ notification.get_status_display }}">
            <h3>{{ notification.get_type_display }}</h3>
            <p>{{ notification.body }}</p>
            <p class="timestamp">il y as {{ notification.date|timesince }}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}